---
title: "dataAdapt"
output: html_document
---

```{r, include = F}
devtools::document()

library(sl3)
library(hal9001fast)
```



```{r}
remotes::install_github("Larsvanderlaan/tmle3", ref = "updating_updater")
#rmultinom(n = 2, c(1,2,3,4,5), rep(1/5,5))
rmults <- function(n, size, prob) {
  size = size[1]
  prob = prob[1]
  apply(rmultinom(n = n, 1:size, rep(prob, size))==1, 2, which)

}
rmults(2, c(5,5), c(1/5,1/5))


library(simcausal)
D <- DAG.empty()
D <- D +
  node("W1", distr = "rmults", size = 15 , prob = 1/15) +
  node("W", distr = "rconst", const = W1 + 1) +
  node("S", distr = "runif",  min = -5, max = 5) +
  node("Y", distr = "rbinom", size =1 , prob = plogis((S ))) + 
    node("pY", distr = "rconst",const = plogis((S )))


setD <- set.DAG(D)
dat <- sim(setD, n = 1500)
dat

```





```{r, include = F}
tmle_spec <- tmle3_Spec_Threshold$new(data_adaptive = T,
                                      threshold_function = function(A) {as.vector(quantile(A, seq(0.05, 0.90, length.out = 10)))})
task <- tmle_spec$make_tmle_task(dat, list("W" = c("W1", "W"), "A" = "S", "Y" = "Y"))
likelihood <- tmle_spec$make_initial_likelihood(task, list("A" = Lrnr_glm$new(), "A_learned" = Lrnr_glm$new(), "Y" = Lrnr_glm$new()))

updater <- tmle_spec$make_updater()
tlik <- tmle_spec$make_targeted_likelihood(likelihood, updater)

params <- tmle_spec$make_params(task, tlik)
(params[[1]]$estimates(task, "validation")$psi)
updater$update(tlik, task)
(params[[1]]$estimates(task, "validation")$psi)
```






```{r, include = F}
library(data.table)
library(origami)
library(delayed)


npsem <- list(define_node("W", "W", c()),
              define_node("A_learned", c("S"), c("A")),
              define_node("A", c("S"), "W"),
              define_node("Y", "Y", c("A")))
dat
task <- tmle3_Task$new(as.data.table(dat), npsem)
lrnr_bin <- make_learner(Lrnr_glm_fast)
cv_lrnr <- make_learner(Pipeline, Lrnr_cv$new(make_learner(Lrnr_glm), full_fit = T))

factor_list <- list(W = LF_emp$new("W"), A_learned = LF_fit$new("A_learned", cv_lrnr, type = "mean"))
likelihood <- Likelihood$new(factor_list)
likelihood <- likelihood$train(task)
data.table(likelihood$get_likelihood(task, "A_learned", fold_number = "validation"), task$get_tmle_node("A"))
generator_R <- learner_marker_task_generator(learned_marker_node = "A_learned", node = "Y")

generator_A <- learner_marker_task_generator(learned_marker_node = "A_learned", node = "A")

  
```

```{r, include = T}
lf_A <- LF_derived$new("A", Lrnr_CDF$new(lrnr_bin,
                                   10,  cutoffs, cv = F), likelihood, generator_A, type = "mean")
lf_R <- LF_derived$new("Y", Lrnr_thresh$new(Lrnr_cv$new(make_learner(Pipeline, lrnr_bin, make_learner(Lrnr_wrapper, 5))), 
                                    strata_variable = "A",
                                    cutoffs = cutoffs), likelihood, generator_R, type = "mean")

lf_R <- LF_derived$new("Y", Lrnr_thresh$new(make_learner(Stack, lrnr_bin, lrnr_bin),
                                    strata_variable = "A", cv = T,
                                    cutoffs = cutoffs), likelihood, generator_R, type = "mean")


lf_R <- LF_derived$new("Y", Lrnr_thresh$new( make_learner(Lrnr_glm, family = binomial()),
                                            strata_variable = "A", cv = F,
                                            cutoffs = cutoffs), likelihood, generator_R, type = "mean")

Lrnr_chainer
likelihood$add_factors(list(lf_A, lf_R))
```

```{r}
#as.data.table(matrix(likelihood$get_likelihood(task, "A", fold_number = "validation"), nrow = 1500))
#as.data.table(matrix(likelihood$get_likelihood(task, "A", fold_number = "validation"), nrow = 1500))
likelihood$get_likelihood(task, "Y", fold_number = "full")
as.data.table(matrix((likelihood$get_likelihood(task, "Y", fold_number = "full")), nrow = 1500))

as.data.table(matrix(likelihood$get_likelihood(task, "A", fold_number = "full"), nrow = 1500))
```

```{r}
as.data.table(matrix(likelihood$get_likelihood(task, "A", fold_number = 1), nrow = 1500))

```



```{R}
x <- c(1,2,3,4,5,6,7,8,9)
near(x,1)
```
