---
title: "EfficientThresh"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include = F}
devtools::install_github("Larsvanderlaan/tmle3", ref = "updating_updater")

```

```{r}
library(tmle3)
library(simcausal)
D <- DAG.empty()
D <- D +
  node("W", distr = "runif", min = -1, max = 1) +
  node("S", distr = "runif",  min = -5, max = 5) +
  node("Y", distr = "rbinom", size =1 , prob = plogis(( -7 + 1 + S + W ))) +
  node("Z", distr = "rbinom", size = 1 , prob = Y*0.5 + (1-Y)*(0.8)) +
  node("pZ", distr = "rconst",const = Y*0.5 + (1-Y)*(0.8)) 
setD <- set.DAG(D)
data <- sim(setD, n = 100500)
mean(data$Y[data$Z==1])
mean(data$Y[data$Z==0])
mean(data$Z[data$Y==1])
mean(data$Z[data$Y==0])
```


```{r}
rmults <- function(n, size, prob) {
  size = size[1]
  prob = prob[1]
  apply(rmultinom(n = n, 1:size, rep(prob, size))==1, 2, which)

}
rmults(2, c(5,5), c(1/5,1/5))


library(simcausal)
D <- DAG.empty()
D <- D +
  node("W1", distr = "rmults", size = 15 , prob = 1/15) +
  node("W", distr = "rconst", const = W1 + 1) +
  node("W2", distr = "rmults", size = 15 , prob = 1/15) +
  node("Wa", distr = "rconst", const = W1 + 1) +
  node("Sd", distr = "rmults",  size = 10, prob = plogis((W-8)/20)) +
  node("S", distr = "rnorm", mean = (W-8)/8) +
  node("Y", distr = "rbinom", size =1 , prob = plogis((S ))) + 
    node("pY", distr = "rconst",const = plogis((S )))


setD <- set.DAG(D)
dat <- sim(setD, n = 1000)
dat

```
```{r}
devtools::install_github("Larsvanderlaan/tmle3", ref = "updating_updater")

```

```{r}
npsem <- list(define_node("W", "W", c()),
     define_node("A", "S", "W"),
     define_node("Y", "Y", c("A", "W")))

task <- tmle3_Task$new(dat, npsem)
```

```{r}
task$npsem$A$variable_type
```
Lrnr_pooled_hazards
```{r}
learner_list <- list(
  "A" = Lrnr_density_discretize$new(),
  "Y" = Lrnr_glm$new()
)

LF_A <- LF_fit$new("A", learner_list[["A"]])
LF_Y <- LF_fit$new("Y", learner_list[["Y"]], type = "mean")
likelihood <- Likelihood$new(list(LF_A, LF_Y))
likelihood <- likelihood$train(task)
tlik <- Targeted_Likelihood$new(likelihood, submodel_type_by_node = list("Y" = "logistic", "A" = "EIC"), updater = list(one_dimensional = T, constrain_step = T, delta_epsilon = list("Y" = 1e-3, "A" = function(x) {
  res = 0.9/max(abs(x))
  
  res <- min(res, 0.1)
  return(res)
}), convergence_type = "scaled_var"))
```



```{r}
library(R6)
mean(-log(tlik$get_likelihood(task, "A")))
param <- Param_thresh_eff$new(tlik, discretize_g = F)
```
1.371835

```{r}
mean(-log(tlik$get_likelihood(task, "A")))
#v=param$clever_covariates(task, node = "A", for_fitting = F)
mean(-log(tlik$get_likelihood(task, "A")))
```
1.354231

```{r, include = T}
for(i in 1:2) {
tlik$updater$update_step(tlik, task)
}
```



```{r}
v = param$clever_covariates(task, for_fitting = T, node = "A")
data.table(apply(v$IC$A,2,var))
weights_A <- 1/apply(v$IC$A,2,var)
weights_A <- weights_A #/(sum(weights_A))
#norm(colMeans(v$IC$A)*sqrt(weights_A), type="2")/sqrt(10)
norm(colMeans(v$IC$A)*1, type="2")/sqrt(10)
print(data.table(v$psi_W))
```


```{r}
longtask <- param$make_long_task(task)
quantile(tlik$get_likelihood(longtask, "A"))
quantile(tlik$get_likelihood(task, "A"))
```

```{r}

mean(-log(tlik$get_likelihood(task, "A")))
```
2.328143

```{r}

dat <-cbind(longtask$get_data(,"trueid"), A = longtask$get_tmle_node("A"), W = longtask$get_tmle_node("W"), Atrue = task$get_tmle_node("A"), Wtrue = task$get_tmle_node("W"), id = task$id)
dat
indv <- which(abs(dat$A - dat$Atrue) < 1e-3 & abs(dat$W - dat$Wtrue) <  1e-3 & dat$id == dat$trueid)

ids <- dat$trueid[indv]
ids <-  as.numeric(as.character((ids)))
data.table(v1$Y[ids,])
data.table(v$Y[indv,])
data.table(v1$Y[ids,]) - data.table(v$Y[indv,] )
 data.table(v1$A[ids,]) - data.table(v$A[indv,] )

```
```{r}
library(dplyr)
long_g_id <- v$long_g_id[,c("id", "g")]
long_g_id
t = proc.time()
 long_g_id[, c(0, cumsum(g)[-length(g)]), by = id]
proc.time() - t
t = proc.time()
long_g_id[, frollsum(.SD, 2, na.rm=T, align = "right"), by = id]
 proc.time() - t
 
 t = proc.time()
 h = 1 -v$cdf[, .SD[5] , by = id][[2]]
 proc.time() - t
```



