---
title: "sim"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
D <- DAG.empty()
D <- D +
  node("W1", distr = "runif", min = -1, max = 1) +
   node("W", distr = "rconst", const = round(W1,1)) +
  node("A", distr = "rbinom", size = 1, prob = plogis((0) ) )+
  node("g", distr = "rconst", const = plogis((0 )) )+
  
    node("gRtilde", distr = "rconst",  const =  plogis( W + 2 *A - 1 )) +
   node("gRtilde1", distr = "rconst",  const =  plogis( W  + 1) ) +
   node("gRtilde0", distr = "rconst",  const =  plogis( W  - 1) ) +
   node("gR", distr = "rconst",  const =  bound(gRtilde, 0.05) ) +
  node("R", distr = "rbinom", size = 1, prob = gR)+
  node("RR", distr = "rconst", const = gRtilde1/gRtilde0)


setD <- set.DAG(D, vecfun = c("bound", "round"))
data <- sim(setD, n = n)
data <- setDT(data)
data$id <- data$ID
data$ID <- NULL
data$t <- 0
data$id <- as.factor(data$id)

setkey(data, id ,t)
data



```



```{r}
library(data.table)
#bias_list_eff
library(ggplot2)
library(gridExtra)
sample_size <- c(1, 2.5, 5, 10, 15)
results <- data.table(
  no_sieve_bias = as.vector(unlist(bias_list_reg)), 
  sieve_bias = as.vector(unlist(bias_list_eff)),
   no_sieve_se = as.vector(unlist(se_list_reg)), 
  sieve_se = as.vector(unlist(se_list_eff)),
  no_sieve_score = as.vector(unlist(score_list_reg)), 
  sieve_score = as.vector(unlist(score_list_eff)),
                      sample_size)
results
results[, f := 1:6, by = "sample_size"]



g1 <- ggplot(results[results$f ==1], aes(x = sample_size, y = no_sieve_score )) + geom_point(se = F)  + scale_x_continuous(
  breaks = sample_size)+ xlab("n (in thousands)") 
g2 <- ggplot(results[results$f ==1], aes(x = sample_size, y = sieve_score )) + geom_point(se = F)  + scale_x_continuous(
  breaks = sample_size) + xlab("n (in thousands)") 

g3 <- ggplot(results[results$f ==2], aes(x = sample_size, y = no_sieve_score )) + geom_point(se = F) + scale_x_continuous(
  breaks = sample_size)+ xlab("n (in thousands)") 
g4 <- ggplot(results[results$f ==2], aes(x = sample_size, y = sieve_score )) + geom_point(se = F) + scale_x_continuous(
  breaks = sample_size)+ xlab("n (in thousands)") 

g5 <- ggplot(results[results$f ==3], aes(x = sample_size, y = no_sieve_score )) + geom_point(se = F) + scale_x_continuous(
  breaks = sample_size)+ xlab("n (in thousands)") 
g6 <- ggplot(results[results$f ==3], aes(x = sample_size, y = sieve_score )) + geom_point(se = F) + scale_x_continuous(
  breaks = sample_size)+ xlab("n (in thousands)") 

g1a <- ggplot(results[results$f ==4], aes(x = sample_size, y = no_sieve_score )) + geom_point(se = F)  + scale_x_continuous(
  breaks = sample_size)+ xlab("n (in thousands)") 
g2a <- ggplot(results[results$f ==4], aes(x = sample_size, y = sieve_score )) + geom_point(se = F) + scale_x_continuous(
  breaks = sample_size)+ xlab("n (in thousands)") 

g3a <- ggplot(results[results$f ==5], aes(x = sample_size, y = no_sieve_score )) + geom_point(se = F) + scale_x_continuous(
  breaks = sample_size)+ xlab("n (in thousands)") 
g4a <- ggplot(results[results$f ==5], aes(x = sample_size, y = sieve_score )) + geom_point(se = F) + scale_x_continuous(
  breaks = sample_size)+ xlab("n (in thousands)") 

g5a <- ggplot(results[results$f ==6], aes(x = sample_size, y = no_sieve_score )) + geom_point(se = F) + scale_x_continuous(
  breaks = sample_size)+ xlab("n (in thousands)") 
g6a <- ggplot(results[results$f ==6], aes(x = sample_size, y = sieve_score )) + geom_point(se = F) + scale_x_continuous(
  breaks = sample_size) + xlab("n (in thousands)") 

grid.arrange(g1, g3, g5, g2, g4,  g6,nrow = 2)
grid.arrange(g1a, g3a, g5a, g2a, g4a,  g6a, nrow = 2)
```







```{r}
library(data.table)
#bias_list_eff
library(ggplot2)
library(gridExtra)
sample_size <- c(2.5, 5, 10, 15)
results <- data.table(
  no_sieve_bias = abs(as.vector(unlist(bias_list_reg))), 
  sieve_bias = abs(as.vector(unlist(bias_list_eff))),
   no_sieve_se = as.vector(unlist(se_list_reg)), 
  sieve_se = as.vector(unlist(se_list_eff)),
                      sample_size)
results[, f := 1:5, by = "sample_size"]

plot_list <- list()
for(i in 1:5) {

  keep <- results$f ==i
  data <- results[keep,]
  print(data)
g1 <- ggplot(data, aes(x = sample_size, y = no_sieve_bias )) + geom_point(se = F) 
g2 <- ggplot(data, aes(x = sample_size, y = sieve_bias )) + geom_point(se = F)

g3 <- ggplot(data, aes(x = sample_size, y = no_sieve_se )) + geom_point(se = F)
g4 <- ggplot(data, aes(x = sample_size, y = sieve_se )) + geom_point(se = F)
#print(grid.arrange(g1, g3, g2, g4, nrow = 2))

}



```





```{r}

bias_list_reg <- list()
bias_list_eff <- list()
se_list_reg <- list()
se_list_eff <- list()
score_list_reg <- list()
score_list_eff <- list()
dfs <- list()
dfs1 <- list()
for(k in 1:5) {
  print(k)
  res_bias <- c()
  res_se <- c()
  res_mse <- c()
  for(n in c(2500, 5000, 10000,15000)) {
    key = paste0(k, "%n=", n)
print(n)
scores <- read.csv( paste0("finalResults/GG_sieve_scores_",n,".csv"))[,-1]
initscores <- read.csv(paste0("finalResults/GG_initial_scores_",n,".csv"))[,-1]
risks <- read.csv(paste0("finalResults/GG_risk_estimates",n,".csv"))[,-1]
se <- read.csv(paste0("finalResults/GG_sterrs",n,".csv"))[,-1]

risks10000 <- read.csv(paste0("finalResults/GG_risk_estimates",15000,".csv"))[,-1]
print("scores")
print(sqrt(n)*as.vector(colMeans(abs(initscores), na.rm = T))[k])
print(sqrt(n)*as.vector(colMeans(abs(scores), na.rm = T))[k])
risks1 <- as.vector(apply(risks,2,mean, na.rm = T))
risks1b <- as.vector(apply(risks10000,2,mean, na.rm = T))

splitrisks <- split(risks1, (1:length(risks1)) %%5)
splitrisksb <- split(risks1b, (1:length(risks1)) %%5)
print("CI")
success_xg <- sapply(1:1000, function(i) {
  v <- as.vector(unlist(se[i, ]))
  
  v <- v[c(2*(k-1)+1, 2*(k-1) +2)]
 
  est <- as.vector(unlist(risks[i,((1:ncol(risks)) %% 5) %in% c(4,0)]))
 
  est <- est[c(2*(k-1)+1, 2*(k-1) +2)]
  truth <- splitrisksb$`3`[k]
 
  
  hit <- est[1] - 1.96*v[1] <= truth &  est[1] + 1.96*v[1] >= truth
  return(hit)
})

print(mean(success_xg, na.rm = T))

success_sieve <- sapply(1:1000, function(i) {
  v <- as.vector(unlist(se[i, ]))
  
  v <- v[c(2*(k-1)+1, 2*(k-1) +2)]
 
  est <- as.vector(unlist(risks[i,((1:ncol(risks)) %% 5) %in% c(4,0)]))
 
  est <- est[c(2*(k-1)+1, 2*(k-1) +2)]
  truth <- splitrisksb$`3`[k]
 
  
  hit <- est[2] - 1.96*v[2] <= truth &  est[2] + 1.96*v[2] >= truth
  return(hit)
})
print(mean(success_sieve, na.rm = T))

  print("bias")

v1 <- as.vector(apply((risks[,5*(k-1) + 1, drop = F]- splitrisksb$`3`[k]),2,mean, na.rm = T))
bias_list_reg[[key]] <- v1 * sqrt(n)

v2 <- as.vector(apply((risks[,5*(k-1) + 2, drop = F]- splitrisksb$`3`[k]),2,mean, na.rm = T))
v3 <- as.vector(apply((risks[,5*(k-1) + 4, drop = F]- splitrisksb$`3`[k]),2,mean, na.rm = T))
v4 <- as.vector(apply((risks[,5*(k-1) + 5, drop = F]- splitrisksb$`3`[k]),2,mean, na.rm = T))

bias_list_eff[[key]] <- v2* sqrt(n)
out1 <- sqrt(n)*c(v1,v2, v3, v4)
print(out1)
res_bias <- c(res_bias, out1)

print("se")

v1 <- as.vector(apply((risks[,5*(k-1) + 1, drop = F]- splitrisksb$`3`[k]),2,sd, na.rm = T))
bias_list_reg[[key]] <- v1 * sqrt(n)

v2 <- as.vector(apply((risks[,5*(k-1) + 2, drop = F]- splitrisksb$`3`[k]),2,sd, na.rm = T))
v3 <- as.vector(apply((risks[,5*(k-1) + 4, drop = F]- splitrisksb$`3`[k]),2,sd, na.rm = T))
v4 <- as.vector(apply((risks[,5*(k-1) + 5, drop = F]- splitrisksb$`3`[k]),2,sd, na.rm = T))

se_list_reg[[key]] <- v1 * sqrt(n)


se_list_eff[[key]] <- v2* sqrt(n)
out2 <- sqrt(n)*c(v1,v2, v3, v4)
print(out2)
res_se <- c(res_se, out2)

df <- data.frame(t(data.frame(key = out1)))
df1 <- data.frame(t(data.frame( key = out2)))

print("mse")
print(sqrt(out1^2 + out2^2))
mse <- (sqrt(out1^2 + out2^2))
res_mse <- c(res_mse, mse)
rownames(df) <- c("bias")
rownames(df1) <- c("se")
colnames(df) <- rep(key,3)
colnames(df1) <- rep(key,3)
dfs <- c(dfs, list(df))
dfs1 <- c(dfs1, list(df1))
  }
   data <- data.table(bias = abs(res_bias))

data$est <- rep(c("plugin", "plugin*", "DR", "DR*"),4)
data$n <- c(rep(2500,4), rep(5000,4), rep(10000,4), rep(15000,4))
data
ggplot(data, aes(x = n, y = bias, color = est)) + geom_point() + ylab("sqrt(n) * Absolute Bias") + xlab("Sample size (n)") + geom_line()+ labs(color='Estimator type') + scale_x_continuous(breaks = c(2500, 5000,10000,15000))+
    theme(text = element_text(size=16v),
        axis.text.x = element_text(angle=0, hjust=1))+theme(aspect.ratio=1)
ggsave(paste0("finalResults/k=", k, "_IPW_bias.png"))

data <- data.table(se = abs(res_se))

data$est <- rep(c("plugin", "plugin*", "DR", "DR*"),4)
data$n <- c(rep(2500,4), rep(5000,4), rep(10000,4), rep(15000,4))


ggplot(data, aes(x = n, y = se, color = est)) + geom_point() + ylab("sqrt(n) * Standard Error") + xlab("Sample size (n)") + geom_line()+ labs(color='Estimator type') +
  scale_x_continuous(breaks = c(2500, 5000,10000,15000))+
    theme(text = element_text(size=16),
        axis.text.x = element_text(angle=0, hjust=1))+theme(aspect.ratio=1)

ggsave(paste0("finalResults/k=", k, "_IPW_se.png"))

data <- data.table(mse = abs(res_mse))

data$est <- rep(c("plugin", "plugin*", "DR", "DR*"),4)
data$n <- c(rep(2500,4), rep(5000,4), rep(10000,4), rep(15000,4))


ggplot(data, aes(x = n, y = mse, color = est)) + geom_point()+  ylab("sqrt(n * Mean Squared Error) ") + xlab("Sample size (n)") + geom_line()+ labs(color='Estimator type') +
  scale_x_continuous(breaks = c(2500, 5000,10000,15000))+
    theme(text = element_text(size=16),
        axis.text.x = element_text(angle=0, hjust=1))+theme(aspect.ratio=1)
ggsave(paste0("finalResults/k=", k, "_IPW_mse.png"))
  
  
  }

```


```{r}
ggplot(data, aes(x = n, y = mse, color = est)) + geom_point()+ ylab("sqrt(n * Mean Squared Error) ") + xlab("Sample size (n)") + geom_line()+ labs(color='Estimator type') +
  scale_x_continuous(breaks = c(2500, 5000,10000,15000))+
    theme(text = element_text(size=16),
        axis.text.x = element_text(angle=0, hjust=1))+theme(aspect.ratio=1)
```

```{r}
D <- DAG.empty()
D <- D +
  node("W1f", distr = "runif", min = -1, max = 1) +
  node("W2f", distr = "runif", min = -1, max = 1) +
  node("W3f", distr = "runif", min = -1, max = 1) +
  node("W4f", distr = "runif", min = -1, max = 1) +
  node("W5f", distr = "runif", min = -1, max = 1) +
   node("W1", distr = "rconst", const = round(W1f,1)) +
   node("W2", distr = "rconst", const = round(W2f,1)) +
   node("W3", distr = "rconst", const = round(W3f,1)) +
  
  
  
  node("g", distr = "rconst", const = 0.3 + 0.5*plogis(W1 + W2 +  W3 + sin(W2)   ) )+
  node("A", distr = "rbinom", size = 1, prob = g )+
    node("gRtilde", distr = "rconst",  const =  plogis( -1 + W1 + W2 - cos(W1) + W2^2 + W3 + 2*A)) +
   node("gRtilde1", distr = "rconst",  const =  plogis( -1 + W1 + W2 - cos(W1) + W2^2 + W3 + 2)) +
   node("gRtilde0", distr = "rconst",  const =  plogis(-1 +  W1 + W2 - cos(W1) + W2^2 + W3 + 0)) +
   node("gR", distr = "rconst",  const =  gRtilde ) +
  node("R", distr = "rbinom", size = 1, prob = gR)+
  node("RR", distr = "rconst", const = gRtilde1/gRtilde0)


setD <- set.DAG(D, vecfun = c("bound", "round"))
data <- sim(setD, n = 200000)
data <- setDT(data)
data
f <- (data$W1 + data$W2 + data$W3  ) 

true_risk <- mean(-data$gRtilde1 * f + (data$gRtilde0 + data$gRtilde1) * log(1 + exp(f)))
true_risk

true_risk <- mean(data$R/(ifelse(data$A ==1, data$g, 1-data$g)) *(-A * f + log(1 + exp(f))))
true_risk

```

```{r}
risk_estimates
results_sieve
quantile(Qg1 )
quantile(Qg0)
data
plot(data$g, g1new)
```

```{r}

colMeans(risk_estimates, na.rm  = T)

(0.7068089 - 0.7111728) * sqrt(n)
```


```{r}
results_xg <- data.frame(matrix(NA, nrow = 1000, ncol = 15))
results_sieve <- data.frame(matrix(NA, nrow = 1000, ncol = 15))
risk_estimates <- data.frame(matrix(NA, nrow = 1000, ncol = 5*5))
stnd_errors <- data.frame(matrix(NA, nrow = 1000, ncol = 5*2))


for(i in 1:100){
  st_errs <- c()
  try({
  print(i)
  n = 5000
library(simcausal)
library(data.table)
bound <- Vectorize(tmle3::bound)
D <- DAG.empty()
D <- D +
  node("W1f", distr = "runif", min = -1, max = 1) +
  node("W2f", distr = "runif", min = -1, max = 1) +
  node("W3f", distr = "runif", min = -1, max = 1) +
  node("W4f", distr = "runif", min = -1, max = 1) +
  node("W5f", distr = "runif", min = -1, max = 1) +
   node("W1", distr = "rconst", const = round(W1f,1)) +
   node("W2", distr = "rconst", const = round(W2f,1)) +
   node("W3", distr = "rconst", const = round(W3f,1)) +
  
  
  node("g", distr = "rconst", const = 0.3 + 0.5*plogis(W1 + W2 +  W3 + sin(W2)   ) )+
  node("A", distr = "rbinom", size = 1, prob = g )+
    node("gRtilde", distr = "rconst",  const =  .1 + .85 *plogis( -1 + W1 + W2 - cos(W1) + W2^2 + W3 + 2*A)) +
   node("gRtilde1", distr = "rconst",  const =  .1 + .85 *plogis( -1 + W1 + W2 - cos(W1) + W2^2 + W3 + 2)) +
   node("gRtilde0", distr = "rconst",  const =  .1 + .85 *plogis(-1 +  W1 + W2 - cos(W1) + W2^2 + W3 + 0)) +
   node("gR", distr = "rconst",  const =  gRtilde ) +
  node("R", distr = "rbinom", size = 1, prob = gR)+
  node("RR", distr = "rconst", const = gRtilde1/gRtilde0)


setD <- set.DAG(D, vecfun = c("bound", "round"))
data <- sim(setD, n = n)
data <- setDT(data)
data$id <- data$ID
data$ID <- NULL
data$t <- 0
data$id <- as.factor(data$id)

setkey(data, id ,t)

#})}





library(tmle3)
library(sl3)
library(uuid)
npsem <- list(define_node("W", c("W1", "W2", "W3"), time = 0, variable_type = variable_type("continuous")), define_node("A", "A", c("W"), time = 0),
             
              define_node("R", "R", c("A", "W"), time = 0,  variable_type = variable_type("binomial")), define_node("RR", "R", c("W"), time = 0,  variable_type = variable_type("continuous")))
task <- tmle3_Task$new(data, npsem, long_format = F)



lrnr <- (Lrnr_hal9001$new(max_degree = 1))

LF_A_bias <- LF_fit$new("A",lrnr)
LF_R_bias <- LF_fit$new("R", lrnr, type = "mean")
factor_list <- list(LF_emp$new("W"), 
                    LF_A_bias,
                     LF_R_bias
)

lik <- Likelihood$new(factor_list)
lik <- lik$train(task)
rev <- make_revere(task, lik, "gen")
library(fda)
library(speedglm)
library(glmnet)
library(stats)

rev_univ <- make_generator(lik, "univ_A")

#1000:  2, 3, 4
#2500: 3,4,5
#5000: 5,6,7
#10000: 7,8, 9
if(n==2500){
   lrnr_fourier <- Lrnr_fourier$new(fourier_basis(3, 1), mult_by = c("Qg1", "Qg0"), screen_RR = T)
} else if(n==5000){
lrnr_fourier <- Lrnr_fourier$new(fourier_basis(5, 1), mult_by = c("Qg1", "Qg0"), screen_RR = T)
} else if(n==10000){
lrnr_fourier <-   Lrnr_fourier$new(fourier_basis(7, 1),  mult_by = c("Qg1", "Qg0"), screen_RR = T)
}  else if(n==15000){
lrnr_fourier <- Lrnr_fourier$new(fourier_basis(10, 1), mult_by = c("Qg1", "Qg0"), screen_RR = T)
}

full_task <- rev_univ(task, "validation")


lrnr_fourier <- lrnr_fourier$train(full_task)


cf_task1 <- task$generate_counterfactual_task(UUIDgenerate(), data.table(A=1))
cf_full_task1 <- rev_univ(cf_task1, "validation")
cf_task0 <- task$generate_counterfactual_task(UUIDgenerate(), data.table(A=0))
cf_full_task0 <- rev_univ(cf_task0, "validation")

xg_score <- c()
sieve_score <- c()
R <- task$get_tmle_node("R")
Q <- lik$get_likelihood(task, "R", "validation")
g <- lik$get_likelihood(task, "A", "validation")
g1 <- ifelse(task$data$A == 1, g, 1- g)
g1new <- lrnr_fourier$predict_fold(full_task, "validation")
gnew <- ifelse(task$data$A == 1, g1new, 1- g1new)

Q1 <- lik$get_likelihood(cf_task1, "R", "validation")
Q0 <- lik$get_likelihood(cf_task0, "R", "validation")

#Qnew1 <- lrnr_fourier$predict_fold(cf_full_task1, "full")
#Qnew0 <- lrnr_fourier$predict_fold(cf_full_task0, "full")
old_score <- c()
new_score <- c()

risks <- c()
A <- task$data$A
Qg1 <- unlist(full_task$get_data(,"Qg1"))
Qg0 <- unlist(full_task$get_data(,"Qg0"))

f <- (task$data$W1 + task$data$W2 + task$data$W3  ) 
score1 <-  mean(Qg1 * f * (A - g1))
score2 <-  mean(Qg1 * log(1 + exp(f)) * (A - g1))
score3 <- mean(Qg0 * log(1 + exp(f)) * (1-A - (1-g1)))
score1a <-  mean(Qg1 * f * (A - g1new))
score2a <-  mean(Qg1 * log(1 + exp(f)) * (A - g1new))
score3a <- mean(Qg0 * log(1 + exp(f)) * (1-A - (1-g1new)))
old_score <- c(old_score, score1, score2, score3)
new_score <- c(new_score,score1a, score2a, score3a) 

old_risk <- mean(task$data$R/g *(-A * f + log(1 + exp(f))))
new_risk <- mean(task$data$R/gnew *(-A * f + log(1 + exp(f))))

true_risk <- mean(-data$gRtilde1 * f + (data$gRtilde0 + data$gRtilde1) * log(1 + exp(f)))
print(true_risk)



eff_risk <- (A/g * (-f + log(1 + exp(f))) + 
  (1-A)/g * log(1 + exp(f)) ) * (R - Q) +
  Q1* (-f + log(1 + exp(f))) + Q0* log(1 + exp(f))

se1 <- sd(eff_risk) / sqrt(n)

eff_risk <- mean(eff_risk)

eff_risk2 <- (A/gnew * (-f + log(1 + exp(f))) + 
  (1-A)/gnew * log(1 + exp(f)) ) * (R - Q) +
  Q1* (-f + log(1 + exp(f))) + Q0* log(1 + exp(f))
se2 <- sd(eff_risk2) / sqrt(n)
eff_risk2 <- mean(eff_risk2)


risks <- c(risks, old_risk, new_risk, true_risk, eff_risk, eff_risk2)
st_errs <-  c(st_errs, se1, se2)



f <- (task$data$W1 + task$data$W2 + task$data$W3  ) *Qg0
score1 <-  mean(Qg1 * f * (A - g1))
score2 <-  mean(Qg1 * log(1 + exp(f)) * (A - g1))
score3 <- mean(Qg0 * log(1 + exp(f)) * (1-A - (1-g1)))
score1a <-  mean(Qg1 * f * (A - g1new))
score2a <-  mean(Qg1 * log(1 + exp(f)) * (A - g1new))
score3a <- mean(Qg0 * log(1 + exp(f)) * (1-A - (1-g1new)))
old_score <- c(old_score, score1, score2, score3)
new_score <- c(new_score,score1a, score2a, score3a) 

old_risk <- mean(task$data$R/g *(-A * f + log(1 + exp(f))))
new_risk <- mean(task$data$R/gnew *(-A * f + log(1 + exp(f))))
true_risk <- mean(-data$gRtilde1 * f + (data$gRtilde0 + data$gRtilde1) * log(1 + exp(f)))
eff_risk <- (A/g * (-f + log(1 + exp(f))) + 
  (1-A)/g * log(1 + exp(f)) ) * (R - Q) +
  Q1* (-f + log(1 + exp(f))) + Q0* log(1 + exp(f))
se1 <- sd(eff_risk) / sqrt(n)
eff_risk <- mean(eff_risk)

eff_risk2 <- (A/gnew * (-f + log(1 + exp(f))) + 
  (1-A)/gnew * log(1 + exp(f)) ) * (R - Q) +
  Q1* (-f + log(1 + exp(f))) + Q0* log(1 + exp(f))
se2 <- sd(eff_risk2) / sqrt(n)
eff_risk2 <- mean(eff_risk2)


risks <- c(risks, old_risk, new_risk, true_risk, eff_risk, eff_risk2)
st_errs <-  c(st_errs, se1, se2)








f <- (task$data$W1 + task$data$W2 + task$data$W3  ) *Qg1
score1 <-  mean(Qg1 * f * (A - g1))
score2 <-  mean(Qg1 * log(1 + exp(f)) * (A - g1))
score3 <- mean(Qg0 * log(1 + exp(f)) * (1-A - (1-g1)))
score1a <-  mean(Qg1 * f * (A - g1new))
score2a <-  mean(Qg1 * log(1 + exp(f)) * (A - g1new))
score3a <- mean(Qg0 * log(1 + exp(f)) * (1-A - (1-g1new)))
old_score <- c(old_score, score1, score2, score3)
new_score <- c(new_score,score1a, score2a, score3a) 

old_risk <- mean(task$data$R/g *(-A * f + log(1 + exp(f))))
new_risk <- mean(task$data$R/gnew *(-A * f + log(1 + exp(f))))
true_risk <- mean(-data$gRtilde1 * f + (data$gRtilde0 + data$gRtilde1) * log(1 + exp(f)))
eff_risk <- (A/g * (-f + log(1 + exp(f))) + 
  (1-A)/g * log(1 + exp(f)) ) * (R - Q) +
  Q1* (-f + log(1 + exp(f))) + Q0* log(1 + exp(f))
se1 <- sd(eff_risk) / sqrt(n)
eff_risk <- mean(eff_risk)

eff_risk2 <- (A/gnew * (-f + log(1 + exp(f))) + 
  (1-A)/gnew * log(1 + exp(f)) ) * (R - Q) +
  Q1* (-f + log(1 + exp(f))) + Q0* log(1 + exp(f))
se2 <- sd(eff_risk2) / sqrt(n)
eff_risk2 <- mean(eff_risk2)


risks <- c(risks, old_risk, new_risk, true_risk, eff_risk, eff_risk2)
st_errs <-  c(st_errs, se1, se2)




f <- log(data$RR)
score1 <-  mean(Qg1 * f * (A - g1))
score2 <-  mean(Qg1 * log(1 + exp(f)) * (A - g1))
score3 <- mean(Qg0 * log(1 + exp(f)) * (1-A - (1-g1)))
score1a <-  mean(Qg1 * f * (A - g1new))
score2a <-  mean(Qg1 * log(1 + exp(f)) * (A - g1new))
score3a <- mean(Qg0 * log(1 + exp(f)) * (1-A - (1-g1new)))
old_score <- c(old_score, score1, score2, score3)
new_score <- c(new_score,score1a, score2a, score3a) 

old_risk <- mean(task$data$R/g *(-A * f + log(1 + exp(f))))
new_risk <- mean(task$data$R/gnew *(-A * f + log(1 + exp(f))))
true_risk <- mean(-data$gRtilde1 * f + (data$gRtilde0 + data$gRtilde1) * log(1 + exp(f)))
eff_risk <- (A/g * (-f + log(1 + exp(f))) + 
  (1-A)/g * log(1 + exp(f)) ) * (R - Q) +
  Q1* (-f + log(1 + exp(f))) + Q0* log(1 + exp(f))
se1 <- sd(eff_risk) / sqrt(n)
eff_risk <- mean(eff_risk)

eff_risk2 <- (A/gnew * (-f + log(1 + exp(f))) + 
  (1-A)/gnew * log(1 + exp(f)) ) * (R - Q) +
  Q1* (-f + log(1 + exp(f))) + Q0* log(1 + exp(f))
se2 <- sd(eff_risk2) / sqrt(n)
eff_risk2 <- mean(eff_risk2)


risks <- c(risks, old_risk, new_risk, true_risk, eff_risk, eff_risk2)
st_errs <-  c(st_errs, se1, se2)




f <- log(1/data$RR)
score1 <-  mean(Qg1 * f * (A - g1))
score2 <-  mean(Qg1 * log(1 + exp(f)) * (A - g1))
score3 <- mean(Qg0 * log(1 + exp(f)) * (1-A - (1-g1)))
score1a <-  mean(Qg1 * f * (A - g1new))
score2a <-  mean(Qg1 * log(1 + exp(f)) * (A - g1new))
score3a <- mean(Qg0 * log(1 + exp(f)) * (1-A - (1-g1new)))
old_score <- c(old_score, score1, score2, score3)
new_score <- c(new_score,score1a, score2a, score3a) 

old_risk <- mean(task$data$R/g *(-A * f + log(1 + exp(f))))
new_risk <- mean(task$data$R/gnew *(-A * f + log(1 + exp(f))))
true_risk <- mean(-data$gRtilde1 * f + (data$gRtilde0 + data$gRtilde1) * log(1 + exp(f)))
eff_risk <- (A/g * (-f + log(1 + exp(f))) + 
  (1-A)/g * log(1 + exp(f)) ) * (R - Q) +
  Q1* (-f + log(1 + exp(f))) + Q0* log(1 + exp(f))
se1 <- sd(eff_risk) / sqrt(n)
eff_risk <- mean(eff_risk)

eff_risk2 <- (A/gnew * (-f + log(1 + exp(f))) + 
  (1-A)/gnew * log(1 + exp(f)) ) * (R - Q) +
  Q1* (-f + log(1 + exp(f))) + Q0* log(1 + exp(f))
se2 <- sd(eff_risk2) / sqrt(n)
eff_risk2 <- mean(eff_risk2)


risks <- c(risks, old_risk, new_risk, true_risk, eff_risk, eff_risk2)
st_errs <-  c(st_errs, se1, se2)


results_sieve[i,] <- new_score
results_xg[i,] <- old_score
risk_estimates[i,] <- risks 
stnd_errors[i,] <- st_errs

 write.csv(results_sieve, paste0("finalResults/GG_sieve_scores_",n,".csv"))
 write.csv(results_xg, paste0("finalResults/GG_initial_scores_",n,".csv"))
 write.csv(risk_estimates, paste0("finalResults/GG_risk_estimates",n,".csv"))
  write.csv(stnd_errors, paste0("finalResults/GG_sterrs",n,".csv"))

})
}
```
