---
title: "LRR"
output: html_document
---


```{r}
bound <- Vectorize(tmle3::bound)
plogis(0)
```


```{r}

do_once <- function(){
library(hal9001fast)
library(data.table)
library(simcausal)
D <- DAG.empty()
D <- D +
  node("W1", distr = "runif", min = -2, max = 2) +
   node("W", distr = "rconst", const = round(W1,1)) +
  node("A", distr = "rbinom", size = 1, prob = 0.5) +
  node("R", distr = "rbinom", size = 1, prob = plogis(.2 + .5 * W - .7*A + .1*A*W ) )+
  node("R1", distr = "rconst", const =  plogis(.2 + .5* W - .7 + .1*W)) +
    node("R0", distr = "rconst", const =  plogis(.2 + .5 *W) ) +
      node("RR", distr = "rconst", const = (R1/R0) ) +
  node("LRR", distr = "rconst", const = log(RR) ) 

setD <- set.DAG(D, vecfun = c("bound", "round"))
data <- sim(setD, n = 500)
data <- setDT(data)
data$id <- data$ID
data$ID <- NULL
data$t <- 0
data$id <- as.factor(data$id)
table(data$R)
table(data$A)
table(data$R[data$A==1])
table(data$R[data$A==0])
setkey(data, id ,t)

library(tmle3)
library(sl3)
npsem <- list(define_node("W", "W", time = 0, variable_type = variable_type("continuous")), define_node("A", "A", c("W"), time = 0), 
              define_node("R", "R", c("W", "A"), time = 0), define_node("RR", "R", c("W"), time = 0))
task <- tmle3_Task$new(data, npsem, long_format = F)

IPW_RR<- function(tmle_task, g, smoothness = 1) {
  task <- tmle_task$get_regression_task("RR")
  R <- tmle_task$get_tmle_node("R", format = T)$R
  W <- tmle_task$get_tmle_node("W", format = T)$W
   A <- tmle_task$get_tmle_node("A", format = T)$A
  g <- 0.5

  keep <- R==1
  print(sum(keep))
  print(length(keep))
  weights <- (R/g)
  Y <- A
  X <- W
  basis_list <- hal9001fast::enumerate_basis(as.matrix(X), max_degree = 3, order_map = c(smoothness), include_zero_order = T, include_lower_order = T)

  x_basis <- hal9001fast::make_design_matrix(as.matrix(X), basis_list)
 
  # fit <- glmnet::cv.glmnet(x_basis[keep,], Y[keep], family = "binomial", weights = weights[keep], standardize = F, nlambda = 200, thresh = 1e-10)
  # 
  # lambda = min(fit$lambda)
  # 
  # lambda = exp(seq(log(lambda), log(lambda / 50000), length.out = 200))
  #  print(lambda)
  # fit <- glmnet::glmnet(x_basis[keep,], Y[keep], family = "binomial", weights = weights[keep], standardize = F, nlambda = 200, thresh = 1e-10, lambda = lambda)
  fit <- glmnet::cv.glmnet(x_basis[keep,], Y[keep], family = "binomial", weights = weights[keep], standardize = F, nlambda = 200)
  fit <- glmnet::glmnet(x_basis[keep,], Y[keep],  family = "binomial", weights = weights[keep], standardize = F, lambda = fit$lambda.min )
  return(list(fit = fit, X = x_basis))
}
out <- IPW_RR(task, likelihood)


pred <- predict(out$fit, newx = out$X, type = "link")


pred1 <- exp(pred)

true <- data$RR

data.table(pred,  data$LRR)
data.table(pred1, true)
data.table(true)
mean(pred1)

mean(true)
return(pred1 - true)
}
```


```{r}
res <- c()
for(i in 1:100) {
  invisible(res <- c(res, mean(do_once())))
}
hist(res)

```

```{r}
quantile(res, c(0.025, 0.975))
hist(res)
```

