
```{r, include=F}
#remotes::install_github("Larsvanderlaan/tmle3", ref = "devel")


devtools::document()
```


```{r}

f = list("aa"= list("a" = "a"))
g = list("bb" = list("b" = "b" ))
c(g, (f))
```

```{r}


# Generate simple causal model
library(simcausal)

D <- DAG.empty()
D <- D +
  node("W", distr = "runif", min =-1, max = 1) +
  node("A", distr = "rbinom", size = 1, prob = 0.5 + W/4 ) +
  node("T", distr = "rexp", rate = 0.05*(1 + 0.5*A - 0.3*W) )+
  node("C", distr = "rexp",  rate = 0.03*(1 + 0.4*A - 0.2*W)) +
  node("Delta", distr = "rconst", const = as.numeric(T<=C)  ) +
  node("Ttilde", distr = "rconst", const = round(min(T,C,10) +1  ))
setD <- set.DAG(D)
dat <- sim(setD, n = 1e2)
# only grab ID, W's, A, T.tilde, Delta
Lname <- grep("W", colnames(dat), value = TRUE)
Aname <- grep("A", colnames(dat), value = TRUE)
df <- dat[, c("ID", Lname, Aname, "T", "C", "Delta", "Ttilde")]

data <- df[,c( "W", "A", "Ttilde", "Delta")]
data$id = df$ID

data$t <- data$Ttilde 
data = data.table(data)
data$processA = as.numeric(data$Delta ==0)
data$processN = as.numeric(data$Delta ==1)
data_baseline <- data
data_baseline$t =0
data_baseline$processA = 0
data_baseline$processN = 0
data_baseline$Ttilde = NA
data_baseline$Delta = NA
data = rbind(data_baseline, data)
data$Ttilde = NULL
data$Delta = NULL
data$at_risk = 1 - (data$processA + data$processN)
data[which(data$processN==1), "processA"] = 0
npsem = list(define_lnode("W", c("W"), time =0), 
     define_lnode("A", c("A"), c("W"), time =0, summary_functions = make_summary_measure_baseline(c("W"))),
     
     define_lnode("processA", c("processA"),  c("A","W"), time = "pooled",times_to_pool = seq(1,max(data$t)), summary_functions = make_summary_measure_baseline(c("A", "W")),
                  at_risk_summary_function = make_summary_measure_last_value("at_risk", strict_past  = T), node_type = "counting_process",
                  include_competing_risks = F),
     
define_lnode("processN", c("processN"), c("A","W"),time = "pooled",times_to_pool = seq(1,max(data$t)), summary_functions = make_summary_measure_baseline(c("A", "W")),
                  at_risk_summary_function = make_summary_measure_last_value("at_risk", strict_past = T), node_type = "counting_process",
                  include_competing_risks = F))
# Delta is the counting process which is 1 at death
```

```{r}

node <- "x"
data <- x
data
helper <- function(x){
  
  id <- x$id
  t <- x$t
  index <- which(data$id == id &  data$t==t)
  print(c(id,t,index))
  if(length(index)>0){
    #If t and id in data then replace
    set(data, index, node, x[, node, with = F])
  
    return(1)
  } else {
    
    #otherwise add new row
    indices<-which(data$id == id & data$t <= t)
    index <- indices[which.max(data[indices, "t", with = F][[1]])]
    print(index)
    new_row <- data[index,]
    set(new_row, , node, x[, node, with = F])
    set(new_row, , "t", x[, "t", with = F])
    print(new_row)
    data <<- rbind(data, new_row)
    print(data)
    return(0)
  }

}
v = y[, helper(.SD), by = c("id", "t"), .SDcols = colnames(y)]

data
```

```{r}
data

```

```{r}
dat = task$data
sum(dat$t==2)
new_dat <- task$get_tmle_node("processN", include_time = T)
new_dat
set(new_dat, ,"processN", 1)


new_dat
newer_dat = task$generate_counterfactual_task(UUIDgenerate(), new_dat)

newer_dat
```

```{r}
newer_dat[1:10]$get_regression_task("processN")$data
```




```{r}
task = ltmle3_Task$new(data, npsem)

 
lik = generate_likelihood_surv(task)
lik = lik$train(task)
```

```{r}
task = ltmle3_Task$new(data, npsem)
task$data
target_node = "processN"
parent_data <- do.call(cbind, lapply(c("W", "A"), task$get_tmle_node, include_id = F, include_time = F, format = T))

outcome_data <- task$get_tmle_node(target_node, format = TRUE, include_id = T, include_time = T, force_time_value = 2)

dat <- cbind(parent_data, outcome_data)
dat

```



```{r}
task = ltmle3_Task$new(data, npsem)
#task$data
v=lapply(1:11, function(i) task$get_tmle_node("processN", force_time_value = 1))

```


```{r}

sampler <- Sampler$new(lik, c("W", "A", "processN"), "W")
data.table(sampler$sample_from_node(task, "A"))
#sampler$compute_conditional_mean(task, "W", "A")
```

```{r}
tlik = Targeted_Likelihood_pooled$new(lik, updater = tmle3_Update$new(one_dimensional = T,constrain_step=T, delta_epsilon = 0.1, maxit = 100))
param <- Param_survival$new(tlik, intervention_list = list("A" = LF_static$new("A", value = 1)), outcome_node = "processN")
param$get_EIC_var(task)
```


```{r}

param <- Param_survival$new(tlik, intervention_list = list(), outcome_node = "processN")

#subdata<- tlik$updater$generate_submodel_data(tlik, task, update_node_key = "processN")



```




```{r}

tlik$updater$update(tlik, task)
```

```{r}
tlik$get_likelihood(task, "processN")
lik$get_likelihood(task, "processN")
```


```{r}
lik$get_likelihood(task, "processN")
tlik$get_likelihood(task, "processN")
```


```{r}
 eps = tlik$updater$fit_submodel(subdata)
coef(eps)
preds<- predict(eps, type = "response")
obs <- subdata$observed[[1]]
mean(subdata$loss(preds,obs))
mean(subdata$loss(subdata$initial[[1]],obs))
data.table(subdata$H[[1]])
data.table(cbind(preds, subdata$initial[[1]],subdata$observed[[1]]))
data.table(cbind(task$get_regression_task("processN", drop_censored = T)$data[,processN],preds, subdata$observed[[1]]))
```

```{r}
sub <- tlik$updater$fit_submodel(subdata)
dim(sub$H)
H <- unlist(sub$H, use.names = F)

obs <- sub$observed
init <- sub$initial
 data.table(sub$H)
data.table(obs)
data.table(init)

 fit = glm(observed ~ H - 1, sub,
                                offset = qlogis(init),
                                family = binomial(),
                                start = rep(0, 1))
coef(fit)

```


```{R}
data.table(subdata$initial$processN)

new=plogis(qlogis(as.vector(subdata$initial$processN)) + subdata$H$processN %*% eps)
data.table(new)
```


```{r}

# Generate simple causal model
library(simcausal)

D <- DAG.empty()
D <- D +
  node("L0", distr = "runif", min =0, max = 1) +
  node("A0", distr = "rbinom", size = 1, prob = 0.5) +
  node("L1", distr = "runif", min =0, max = 1 + 0.5*A0) +
  node("A1", distr = "rbinom", size = 1, prob = L0/8 + .15 + .5 * as.numeric(A0 > .75)) +
  node("Y", distr = "rnorm", mean = A1 + 0.5* A0 - L0 - 0.5*L1  )
setD <- set.DAG(D)
dat <- sim(setD, n = 2e2)
# only grab ID, W's, A, T.tilde, Delta
Lname <- grep("L", colnames(dat), value = TRUE)
Aname <- grep("A", colnames(dat), value = TRUE)
df <- dat[, c("ID", Lname, Aname, "Y")]
df
# The simulator will generate death at time 0.
# our package only allow positive integer time, so I add one to all times
name0 <- grep("0", colnames(dat), value = TRUE)
name1 <- grep("1", colnames(dat), value = TRUE)
df1 = df[,name0]
df1$t <- rep(1, nrow(df1))
colnames(df1) = c("L", "A", "t")
df2 = df[,name1]
df2$t <- rep(2, nrow(df2))
colnames(df2) = c("L", "A", "t")
final <- rbind(df1, df2)
final$Y <- c(rep(NA, nrow(df1)), df$Y)
final$id <- c(df$ID, df$ID)
final <- data.table(final[,c("id", "t", "L", "A", "Y")])
final
```





```{r}
final$A_at_risk = c(rep(1,200), rep(1,200))

npsem <- generate_npsem(final, "L", "L", "A", "Y")

task = ltmle3_Task$new(final, npsem)

tsk = task$get_regression_task("A1", drop_censored = F)
tsk$get_data()
tsk$X
likelihood <- generate_likelihood(task)

```





```{r}
k=likelihood$train(task)
(likelihood$get_likelihood(task, "Y"))

```


```{r}
reduce_f <- function(x,y){
 
  out = list()
  names_out <- names(x)
  for(i in seq_along(x)){
   
    out[[names_out[i]]] <- cbind(x[[i]], y[[i]])
  }
  return(out)
}
list(list(a=1,b=2,c=3), list(a=1,b=2,c=3)) %>% reduce(reduce_f)
```


```{r}
probs
collapse_nodes <- list("P" = c("L0", "L1", "A0", "A1", "Y"))
factors = c(k$factor_list$A0, k$factor_list$A1)

collapsed_k = Collapsed_Likelihood$new(k,collapse_nodes )
collapsed_k$factor_list

collapsed_k$get_likelihoods(task)
collapsed_k$get_hidden_nodes("P")
```

```{r}
collapsed_k$factor_list

```

```{r}
c=LF_emp$new(c("a","b"))
c$name
```

```{r}

lik = generate_likelihood(task)
lik$validate_task(task)

lik$train(task)
```

```{r}
task$weights

```


```{r}
lik1 = lik$train(task)

lik1$get_likelihoods(task)
lik1$get_likelihoods(task, "L0")
```

```{r}

devtools::document()
```


