---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Sampling
library(simcausal)


sim_data <- function(n, bias = F) {
   
D <- DAG.empty()
D <- D +
  node("Wcont", distr = "runif", min = -0.8 , max = 0.8) +
   node("W", distr = "rconst", const = round(Wcont, 1)) +
  node("W1cont", distr = "runif", min = -1, max = 1) +
   node("W1", distr = "rconst", const = round(W1cont, 1)) +
  node("Z", distr = "runif", min = 4, max = 5) +
  node("bias", distr = "rconst", const = bias * Z / n^(0.25) ) + 
  node("g1", distr = "rconst", const =  0.3 +0.4* plogis(bias + W1^2 - W1/2 + W^2 - 0.5*0.5 + 0.5*W - W*W1 - W*sin(W1) + W1*cos(W))) +
  node("A", distr = "rbinom", size = 1,  prob = g1) +
  node("Y", distr = "rbinom", size =1 , prob = plogis(( bias + A + W - A*W1/2 + W1*W + 0.5*sin(W) + exp(W1)*W1 - W^2 ))) +
  node("EY", distr = "rconst", const = plogis(( bias + A + W - A*W1/2 + W1*W + 0.5*sin(W) + exp(W1)*W1 - W^2 ))) +
  node ("EY1", distr = "rconst", const =   plogis(( 1 + W - 1*W1/2 + W1*W + 0.5*sin(W) + exp(W1)*W1 - W^2 ))) 
setD <- set.DAG(D)
data <- sim(setD, n = n)
data <- as.data.table(data)
data
}
data_bias <-sim_data(n , T)
data_bias
```







```{r}
# results <- data.frame(Pnlast = NA, ICtilde = NA, est_sec = NA, est_first = NA, est_standard = NA)
# results <- results[rep(NA, 1000),]

for(i in 1:500){

n = 500
data <- sim_data(n, F)
bias <- runif(n , min = 0.5, max = 1) * 0.75/n^(0.25)
gbias <- bound(data$g1 + bias, 0.05)
Qbias <- bound(data$EY + bias, 0.05)

data_bias <-sim_data(n , T)

lf_A_bias <- LF_known$new("A", mean_fun = function(...) {return(gbias)}, type = "mean")
lf_Y_bias <- LF_known$new("Y", mean_fun = function(...) {return(Qbias)}, type = "mean")

npsem <- list(
  define_node("W", c("W", "W1"), c()),
  define_node("A", "A",  c("W")),
  define_node("Y",  "Y", c("A", "W"))
)

task <- tmle3_Task$new(data, npsem)
task_bias <- tmle3_Task$new(data_bias, npsem)

lrnr <- Lrnr_xgboost$new(max_depth = 5, gamma = 0.05, lambda = 0.1)

lrnr_undersmooth <- Lrnr_undersmooth$new()
lrnr_undersmoothA <- lrnr_undersmooth
lrnr_undersmoothY <- lrnr_undersmooth
lrnr_undersmoothY <- lrnr_undersmoothY$train(task$get_regression_task("Y"))
lrnr_undersmoothA <- lrnr_undersmoothA$train(task$get_regression_task("A"))

num_lambda_Y <- ncol(as.data.table(lrnr_undersmoothY$predict(task$get_regression_task("Y"))))
num_lambda_A <-  ncol(as.data.table(lrnr_undersmoothA$predict(task$get_regression_task("A"))))

factor_list <- list(
  LF_emp$new("W"),
  lf_A_bias,
  lf_Y_bias
)

# factor_list <- list(
#   LF_emp$new("W"),
#   LF_fit$new("A",lrnr, type = "mean"),
#   LF_fit$new("Y", Lrnr_mean$new(), type = "mean")
# )

likelihood <- Likelihood$new(factor_list)

likelihood <- likelihood$train(task_bias)

get_lik_tilde <- function(indexA, indexY) {
  lf_Y <- LF_known$new("Y", mean_fun = function(task) {
  lrnr_undersmoothY$predict(task)[,indexY]
}, type = "mean")
lf_A <- LF_known$new("A", mean_fun = function(task) {
  lrnr_undersmoothA$predict(task)[,indexA]
}, type = "mean")
factor_list_tilde <- list(
  LF_emp$new("W"),
  lf_A,#LF_fit$new("A",lrnr_undersmoothA, type = "mean" ),
  lf_Y #LF_fit$new("Y",lrnr_undersmoothY, type = "mean" )
)
likelihood_tilde <- Likelihood$new(factor_list_tilde)
likelihood_tilde <- likelihood_tilde$train(task)
return(likelihood_tilde)
}


index_Y <- 1
thresh <- 0.8 / sqrt(n) / log(n)
eic_tilde_history_A <- c()


for(index_A in seq_len(num_lambda_A)) {
 break
  print(paste0("A", index_A))
  likelihood_tilde <- get_lik_tilde(index_A, index_Y)
  tlik <- Targeted_Likelihood$new(likelihood, updater = list(maxit = 300, convergence_type = "scaled_var", cvtmle = F, constrain_step = T, one_dimensional = T, delta_epsilon = c( 0.05)))
param <- Param_TSM_higher_order$new(tlik, likelihood_tilde)
  tlik$updater$update(tlik, task)
  est <- param$estimates(task)
  ICtildeA <- mean(est$ICtilde[,1])
  print(ICtildeA)
  eic_tilde_history_A <- c(eic_tilde_history_A, ICtildeA)
  if(abs(ICtildeA) <= thresh) {
    print("convergedA")
    break
  }
}
#index_A <- which.min(abs(eic_tilde_history_A))
index_A <- 1
print(eic_tilde_history_A)
converged <- F


while(!converged) {
  
  eic_tilde_history_Y <- c()
  eic_vec <- c()
  search_set <- seq_len(min(num_lambda_Y,num_lambda_A))
  #search_set <- search_set[search_set <= index_A + 8]
  for(index_Y in search_set) {
    index_A <- index_Y
print(paste0("y: ", index_A, ", ", index_Y))

    likelihood_tilde <- get_lik_tilde(index_A, index_Y)
    
    tlik <- Targeted_Likelihood$new(likelihood, updater = list(maxit = 300, convergence_type = "scaled_var", cvtmle = F, constrain_step = T, one_dimensional = T, delta_epsilon = c( 0.05)))
    param <- Param_TSM_higher_order$new(tlik, likelihood_tilde)
    
    tlik$updater$update(tlik, task)
    est <- param$estimates(task)
    ICtildeY <- mean(rowSums(est$ICtilde))
    ICtildeA <- abs(mean(est$ICtilde[,1]))
        

    eic_tilde_history_Y <- c(eic_tilde_history_Y, ICtildeY)
    param$update_last(task)
    lik2 <- tlik$get_likelihood(task, "Y")
    eic <- mean(task$get_tmle_node("A")/tlik$get_likelihood(task, "A") * (task$get_tmle_node("Y") - lik2))
    eic_vec <- c(eic_vec, eic)
    print(c(ICtildeY, eic))
    if(abs(eic) <= thresh &  abs(ICtildeY)<= thresh) {
      break
    }
    
  }
  best_Y <- which(abs(eic_vec) <= thresh & abs(eic_tilde_history_Y) <= thresh)
  print(eic_tilde_history_Y)
  if(length(best_Y) > 0) {
    index_Y <- min(best_Y)
    converged <- T
     print("convergedY")
    break
  } 
  
  #index_A <- index_A + 1
  if(F & index_A > num_lambda_A) {
    index_Y <- which.min(abs(eic) + abs(ICtildeY))
    index_A <- index_A - 1
    converged <- T
    break
  }
  if(T) {
    index_Y <- which.min(abs(eic) + abs(ICtildeY))
    index_A <- index_Y
    converged <- T
    break
  }
  
  
  
}


likelihood_tilde <- get_lik_tilde(index_A, index_Y)

tlik <- Targeted_Likelihood$new(likelihood, updater = list(maxit = 300, convergence_type = "scaled_var", cvtmle = F, constrain_step = T, one_dimensional = T, delta_epsilon = c( 0.05)))
param <- Param_TSM_higher_order$new(tlik, likelihood_tilde)
tlik$updater$update(tlik, task)
est <- param$estimates(task)
est0 <- est$psi
ICtildeY <- mean(rowSums(est$ICtilde))
param$update_last(task)

est <- param$estimates(task)
est1 <- est$psi
lik2 <- tlik$get_likelihood(task, "Y")
eic <- mean(task$get_tmle_node("A")/tlik$get_likelihood(task, "A") * (task$get_tmle_node("Y") - lik2))
print(ICtildeY)
print(eic)
print(paste0("index: ", index_A, ", ", index_Y))


tlik_old <- Targeted_Likelihood$new(likelihood, updater = list(cvtmle = F))
param_old <- tmle3::Param_TSM$new(tlik_old, list(LF_static$new("A", value = 1)))

tlik_old$updater$update(tlik_old, task)

est <- param_old$estimates(task, fold_number = "full")
est2 <-  est$psi

res <- c(eic, ICtildeY, est0, est1, est2)
print(res)
results[i,] <- res

if(i%%10 ==0 || i ==1) {
  #write.csv(results, "fixedsim1500.csv")
}


}

```

