---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Sampling
library(simcausal)
library(data.table)

sim_data <- function(n, bias = F) {
   
D <- DAG.empty()
D <- D +
  node("Wcont", distr = "runif", min = -0.8 , max = 0.8) +
   node("W", distr = "rconst", const = round(Wcont, 1)) +
  node("W1cont", distr = "runif", min = -1, max = 1) +
   node("W1", distr = "rconst", const = round(W1cont, 1)) +
  node("Z", distr = "runif", min = 4, max = 5) +
  node("bias", distr = "rconst", const = bias * Z / n^(0.25) ) + 
  node("g1", distr = "rconst", const =  0.3 +0.4* plogis(bias + W1^2 - W1/2 + W^2 - 0.5*0.5 + 0.5*W - W*W1 - W*sin(W1) + W1*cos(W))) +
  node("A", distr = "rbinom", size = 1,  prob = g1) +
  node("Y", distr = "rbinom", size =1 , prob = plogis(( bias + A + W - A*W1/2 + W1*W + 0.5*sin(W) + exp(W1)*W1 - W^2 ))) +
  node("EY", distr = "rconst", const = plogis(( bias + A + W - A*W1/2 + W1*W + 0.5*sin(W) + exp(W1)*W1 - W^2 ))) +
  node ("EY1", distr = "rconst", const =   plogis(( 1 + W - 1*W1/2 + W1*W + 0.5*sin(W) + exp(W1)*W1 - W^2 ))) 
setD <- set.DAG(D)
data <- sim(setD, n = n)
data <- as.data.table(data)
data
}
data_bias <-sim_data(5000000 , F)
mean(data_bias$EY1)
```




```{r}
length(eic_list)
```

```{r}

mean_fun_A(task)-data$g1
```

```{r}
print(n)
```


```{r}
# results <- data.frame(Pnlast = NA, ICtilde = NA, est_sec = NA, est_first = NA, est_standard = NA)

# results <- results[rep(NA, 1000),]
# eic_tilde_list <- c()
# eic_list <- c()
# est_ho_list <- c()
# est_list <- c()

all_lambda_tilde_truth <- data.frame(matrix(NA, nrow = 1000, ncol = 120))
all_lambda_Pn_truth <- data.frame(matrix(NA, nrow = 1000, ncol = 120))
all_lambda_tilde<- data.frame(matrix(NA, nrow = 1000, ncol = 120))
all_lambda_Pn <- data.frame(matrix(NA, nrow = 1000, ncol = 120))
tmle_est <- data.frame(matrix(NA, nrow = 1000, ncol = 1))
all_lambda_ho_tmle_est<- data.frame(matrix(NA, nrow = 1000, ncol = 120))
all_lambda_second_order_tmle <- data.frame(matrix(NA, nrow = 1000, ncol = 120))




for(i in 1:500){
  try({
print(i)
print(n)
n = 1000
data <- sim_data(n, F)
biasg <- pmin(0.2+abs(0.1 + data$W1/2 + data$W/2 - data$A/3), 0.6) / n^(0.25)
biasQ <- pmin(0.2+abs(0.1 + data$W1/2 + data$W/2 + data$A/3), 0.6) / n^(0.25)
gbias <- bound(data$g1  + biasg, c(0.1, 0.95))
Qbias <- bound(data$EY + biasQ, c(0.1, 0.95))
print(quantile(gbias))
print(quantile(Qbias))
data_bias <-sim_data(n , T)
mean_fun_Y_bias <- function(tmle_task) {
  A <- tmle_task$data[["A"]]
  W1 <- tmle_task$data[["W1"]]
  W <- tmle_task$data[["W"]]
  biasQ <- pmin(0.2+abs(0.1 + W1/2 + W/2 + A/3), 0.6) / n^(0.25)

  bound(plogis(A + W - A*W1/2 + W1*W + 0.5*sin(W) + exp(W1)*W1 - W^2 ) + biasQ, c(0.1, 0.95))
}
mean_fun_Y <- function(tmle_task) {
  A <- tmle_task$data[["A"]]
  W1 <- tmle_task$data[["W1"]]
  W <- tmle_task$data[["W"]]
  plogis((A + W - A*W1/2 + W1*W + 0.5*sin(W) + exp(W1)*W1 - W^2 ))
}
mean_fun_A_bias <- function(tmle_task) {
  A <- tmle_task$data[["A"]]
  W1 <- tmle_task$data[["W1"]]
  W <- tmle_task$data[["W"]]
  biasA <- pmin(0.2+abs(0.1 + W1/2 + W/2 + A/3), 0.6) / n^(0.25)

  bound(0.3 +0.4* plogis(W1^2 - W1/2 + W^2 - 0.5*0.5 + 0.5*W - W*W1 - W*sin(W1) + W1*cos(W)) + biasA, c(0.1, 0.95))
}
mean_fun_A <- function(tmle_task) {
  A <- tmle_task$data[["A"]]
  W1 <- tmle_task$data[["W1"]]
  W <- tmle_task$data[["W"]]
 0.3 +0.4* plogis(W1^2 - W1/2 + W^2 - 0.5*0.5 + 0.5*W - W*W1 - W*sin(W1) + W1*cos(W))
}


lf_A_bias <- LF_known$new("A", mean_fun =mean_fun_A_bias, type = "mean")
lf_Y_bias <- LF_known$new("Y", mean_fun = mean_fun_Y_bias, type = "mean")

lf_A_true <- LF_known$new("A", mean_fun = mean_fun_A, type = "mean")
lf_Y_true <- LF_known$new("Y", mean_fun = mean_fun_Y, type = "mean")

npsem <- list(
  define_node("W", c("W", "W1"), c()),
  define_node("A", "A",  c("W")),
  define_node("Y",  "Y", c("A", "W"))
)

task <- tmle3_Task$new(data, npsem)
task_bias <- tmle3_Task$new(data_bias, npsem)

lrnr <- Lrnr_xgboost$new(max_depth = 5, gamma = 0.05, lambda = 0.1)

lrnr_undersmooth <- Lrnr_undersmooth$new()
lrnr_undersmoothA <- lrnr_undersmooth
lrnr_undersmoothY <- lrnr_undersmooth
lrnr_undersmoothY <- lrnr_undersmoothY$train(task$get_regression_task("Y"))
lrnr_undersmoothA <- lrnr_undersmoothA$train(task$get_regression_task("A"))

num_lambda_Y <- ncol(as.data.table(lrnr_undersmoothY$predict(task$get_regression_task("Y"))))
num_lambda_A <-  ncol(as.data.table(lrnr_undersmoothA$predict(task$get_regression_task("A"))))

factor_list <- list(
  LF_emp$new("W"),
  lf_A_bias,
  lf_Y_bias
)

factor_list_truth <- list(
  LF_emp$new("W"),
  lf_A_true,
  lf_Y_true
)
likelihood_truth <- Likelihood$new(factor_list_truth)

likelihood_truth <- likelihood_truth$train(task)
# factor_list <- list(
#   LF_emp$new("W"),
#   LF_fit$new("A",lrnr, type = "mean"),
#   LF_fit$new("Y", Lrnr_mean$new(), type = "mean")
# )

likelihood <- Likelihood$new(factor_list)

likelihood <- likelihood$train(task_bias)

get_lik_tilde <- function(indexA, indexY) {
  lf_Y <- LF_known$new("Y", mean_fun = function(task) {
  lrnr_undersmoothY$predict(task)[,indexY]
}, type = "mean")
lf_A <- LF_known$new("A", mean_fun = function(task) {
  lrnr_undersmoothA$predict(task)[,indexA]
}, type = "mean")
factor_list_tilde <- list(
  LF_emp$new("W"),
  lf_A,#LF_fit$new("A",lrnr_undersmoothA, type = "mean" ),
  lf_Y #LF_fit$new("Y",lrnr_undersmoothY, type = "mean" )
)
likelihood_tilde <- Likelihood$new(factor_list_tilde)
likelihood_tilde <- likelihood_tilde$train(task)
return(likelihood_tilde)
}

search_set <- seq_len(min(num_lambda_A, num_lambda_Y))
#search_set <- expand.grid(1:30, 1:30)
# order_by <- order(rowSums(search_set) + abs(search_set[,1] - search_set[,2])/2)
# search_set <- search_set[order_by,]
thresh <- 0.2/sqrt(n)/log(n)

for(index in search_set) {
  try({
  #index_A <- search_set[index,2]
  #index_Y <- search_set[index,1]
  index_A <- index
  index_Y <- index
  print(paste0("Y", index_Y, "A", index_A))
  likelihood_tilde <- get_lik_tilde(index_A, index_Y)
  # P0 second order
  tlik <- Targeted_Likelihood$new(likelihood_truth, updater = list(maxit = 300, convergence_type = "scaled_var", cvtmle = F, constrain_step = T, one_dimensional = T, delta_epsilon = c( 0.1)))
    param <- Param_TSM_higher_order$new(tlik, likelihood_tilde)
    
  tlik$updater$update(tlik, task)
  est <- param$estimates(task)
  eictilde <- mean(rowSums(est$ICtilde))
  # P0 first order
  tlik <- Targeted_Likelihood$new(likelihood_truth, updater = list(maxit = 300, convergence_type = "scaled_var", cvtmle = F, constrain_step = T, one_dimensional = T, delta_epsilon = c( 0.1)))
    param <- Param_TSM_higher_order$new(tlik, likelihood_tilde)
  param$update_last(task)
  
  lik2 <- tlik$get_likelihood(task, "Y")
  eic <- mean(task$get_tmle_node("A")/tlik$get_likelihood(task, "A") * (task$get_tmle_node("Y") - lik2))
    est <- param$estimates(task, fold_number = "full")
   est1 <-  est$psi
  eic_truth <- eic
  eictilde_truth <- eictilde
  print(c(eictilde_truth,eic_truth))
  all_lambda_tilde_truth[i, index] <- eictilde_truth
  all_lambda_Pn_truth[i, index] <- eic_truth
  
  likelihood_tilde <- get_lik_tilde(index_A, index_Y)
  tlik <- Targeted_Likelihood$new(likelihood, updater = list(maxit = 300, convergence_type = "scaled_var", cvtmle = F, constrain_step = T, one_dimensional = T, delta_epsilon = c( 0.1)))
    param <- Param_TSM_higher_order$new(tlik, likelihood_tilde)
    
  tlik$updater$update(tlik, task)
  est <- param$estimates(task)
  est0 <- est$psi
  eictilde <- mean(rowSums(est$ICtilde))
  param$update_last(task)
  lik2 <- tlik$get_likelihood(task, "Y")
  eic <- mean(task$get_tmle_node("A")/tlik$get_likelihood(task, "A") * (task$get_tmle_node("Y") - lik2))
    est <- param$estimates(task, fold_number = "full")
   est1 <-  est$psi
   print(c(est0, est1))
   print(c(eictilde, eic))
   all_lambda_tilde[i, index] <- eictilde
    all_lambda_Pn[i, index] <- eic
    all_lambda_second_order_tmle[i,index] <- est0
   all_lambda_ho_tmle_est[i, index] <- est1
   
  })
} 
   
  
tlik_old <- Targeted_Likelihood$new(likelihood, updater = list(cvtmle = F))
param_old <- tmle3::Param_TSM$new(tlik_old, list(LF_static$new("A", value = 1)))
tlik_old$updater$update(tlik_old, task)
est <- param_old$estimates(task, fold_number = "full")
est2 <-  est$psi
print(est2)
tmle_est[i,] <- est2

})
  
  write.csv(all_lambda_tilde_truth, paste0("simSearch/all_lambda_tilde_truth", n, ".csv"))
write.csv(all_lambda_Pn_truth, paste0("simSearch/all_lambda_Pn_truth", n, ".csv"))
write.csv(all_lambda_tilde, paste0("simSearch/all_lambda_tilde", n, ".csv"))
write.csv(all_lambda_Pn, paste0("simSearch/all_lambda_Pn", n, ".csv"))
write.csv(tmle_est, paste0("simSearch/tmle_est", n, ".csv"))
write.csv(all_lambda_ho_tmle_est, paste0("simSearch/all_lambda_ho_tmle_est", n, ".csv"))
write.csv(all_lambda_second_order_tmle, paste0("simSearch/all_lambda_second_order_tmle", n, ".csv"))
}
```


```{r}
  
  write.csv(all_lambda_tilde_truth, paste0("simSearch/dupeall_lambda_tilde_truth", n, ".csv"))
write.csv(all_lambda_Pn_truth, paste0("simSearch/dupeall_lambda_Pn_truth", n, ".csv"))
write.csv(all_lambda_tilde, paste0("simSearch/dupeall_lambda_tilde", n, ".csv"))
write.csv(all_lambda_Pn, paste0("simSearch/dupeall_lambda_Pn", n, ".csv"))
write.csv(tmle_est, paste0("simSearch/dupetmle_est", n, ".csv"))
write.csv(all_lambda_ho_tmle_est, paste0("simSearch/dupeall_lambda_ho_tmle_est", n, ".csv"))
write.csv(all_lambda_second_order_tmle, paste0("simSearch/dupeall_lambda_second_order_tmle", n, ".csv"))

```

