---
title: "Untitled"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include = T, eval = F}
truth <-0.7245819
n = 250
print(n)
est <- read.csv(paste0("biasrerun", n, ".csv"))
tilde<-read.csv( paste0("biasreruntilde", n, ".csv"))
pn<-read.csv( paste0("biasrerunpn", n, ".csv"))
est_old <- read.csv( paste0("biasrerunOldTMLE", n, ".csv"))[[2]]
thresh <- 0.6/sqrt(n)/log(n)
best1 <- which(apply(tilde, 2, mean, na.rm = T) <= thresh & apply(pn, 2, mean, na.rm = T) <= thresh)
print(min(best1))
if(length(best1)==0){
  
  best1 <- which.min(abs(apply(tilde, 2, mean, na.rm = T)) +
                       abs( apply(pn, 2, mean, na.rm = T) <= thresh))
} else{
  best1 <- min(best1)
}

bias_ho <- mean(est[,best1] - truth, na.rm = T)
bias_old <- mean(est_old - truth)
se_ho <- sd(est[,best1] - truth, na.rm = T)
se_old <- sd(est_old - truth)
sqrt(n)*c(bias_ho, se_ho)
sqrt(n)*sqrt(sum(c(bias_ho, se_ho)^2))
sqrt(n)*c(bias_old, se_old)
sqrt(n)*sqrt(sum(c(bias_old, se_old)^2))


n = 500
print(n)
est <- read.csv(paste0("biasrerun", n, ".csv"))
tilde<-read.csv( paste0("biasreruntilde", n, ".csv"))
pn<-read.csv( paste0("biasrerunpn", n, ".csv"))
est_old <- read.csv( paste0("biasrerunOldTMLE", n, ".csv"))[[2]]
thresh <- 0.6/sqrt(n)/log(n)
best1 <- which(apply(tilde, 2, mean, na.rm = T) <= thresh & apply(pn, 2, mean, na.rm = T) <= thresh)
print(min(best1))
if(length(best1)==0){
  
  best1 <- which.min(abs(apply(tilde, 2, mean, na.rm = T)) +
                       abs( apply(pn, 2, mean, na.rm = T) <= thresh))
} else{
  best1 <- min(best1)
}
bias_ho <- mean(est[,best1] - truth, na.rm = T)
bias_old <- mean(est_old - truth)
se_ho <- sd(est[,best1] - truth, na.rm = T)
se_old <- sd(est_old - truth)
sqrt(n)*c(bias_ho, se_ho)
sqrt(n)*sqrt(sum(c(bias_ho, se_ho)^2))
sqrt(n)*c(bias_old, se_old)
sqrt(n)*sqrt(sum(c(bias_old, se_old)^2))


n = 1000
print(n)
est <- read.csv(paste0("biasrerun", n, ".csv"))
tilde<-read.csv( paste0("biasreruntilde", n, ".csv"))
pn<-read.csv( paste0("biasrerunpn", n, ".csv"))
est_old <- read.csv( paste0("biasrerunOldTMLE", n, ".csv"))[[2]]
thresh <- 0.6/sqrt(n)/log(n)
best1 <- which(apply(tilde, 2, mean, na.rm = T) <= thresh & apply(pn, 2, mean, na.rm = T) <= thresh)
print(min(best1))
if(length(best1)==0){
  
  best1 <- which.min(abs(apply(tilde, 2, mean, na.rm = T)) +
                       abs( apply(pn, 2, mean, na.rm = T) <= thresh))
} else{
  best1 <- min(best1)
}
bias_ho <- mean(est[,best1] - truth, na.rm = T)
bias_old <- mean(est_old - truth)
se_ho <- sd(est[,best1] - truth, na.rm = T)
se_old <- sd(est_old - truth)
sqrt(n)*c(bias_ho, se_ho)
sqrt(n)*sqrt(sum(c(bias_ho, se_ho)^2))
sqrt(n)*c(bias_old, se_old)
sqrt(n)*sqrt(sum(c(bias_old, se_old)^2))



n = 1500
print(n)
est <- read.csv(paste0("biasrerun", n, ".csv"))
tilde<-read.csv( paste0("biasreruntilde", n, ".csv"))
pn<-read.csv( paste0("biasrerunpn", n, ".csv"))
est_old <- read.csv( paste0("biasrerunOldTMLE", n, ".csv"))[[2]]
thresh <- 0.6/sqrt(n)/log(n)
best1 <- which(apply(tilde, 2, mean, na.rm = T) <= thresh & apply(pn, 2, mean, na.rm = T) <= thresh)
print(min(best1))
if(length(best1)==0){
  
  best1 <- which.min(abs(apply(tilde, 2, mean, na.rm = T)) +
                       abs( apply(pn, 2, mean, na.rm = T) <= thresh))
} else{
  best1 <- min(best1)
}
bias_ho <- mean(est[,best1] - truth, na.rm = T)
bias_old <- mean(est_old - truth)
se_ho <- sd(est[,best1] - truth, na.rm = T)
se_old <- sd(est_old - truth)
sqrt(n)*c(bias_ho, se_ho)
sqrt(n)*sqrt(sum(c(bias_ho, se_ho)^2))
sqrt(n)*c(bias_old, se_old)
sqrt(n)*sqrt(sum(c(bias_old, se_old)^2))

```







```{r, echo = F}
library(kableExtra)
truth <-0.7245819
n = 250
print(n)
est <- read.csv(paste0("OracleHoTMLE", n, ".csv"))[[2]]
tilde<-read.csv( paste0("oracleEICtilde", n, ".csv"))[[2]]
pn<-read.csv( paste0("oracleEIC", n, ".csv"))[[2]]
est_old <- read.csv( paste0("oracleOldTMLE", n, ".csv"))[[2]]

res1 <- c(sqrt(n) * mean(est - truth), n * var(est - truth))
res2 <- c(sqrt(n) * mean(est_old - truth), n * var(est_old - truth))
res1 <- round(c(res1, sqrt(sum(res1^2))),4)
res2 <- round(c(res2, sqrt(sum(res2^2))),4)
result <- cbind(data.frame(rbind(res1 , res2)), rep(NA,2), rep(NA,2))
colnames(result) <- c("bias", "variance", "SE", "abs_PntildeD2", "abs_PnD1")
rownames(result) <- c("HigherOrder", "FirstTMLE")
result[1,4] <- sqrt(n) * mean(abs(tilde))
result[1,5] <- sqrt(n) * mean(abs(pn))

kable(result)

truth <-0.7245819
n = 500
print(n)
est <- read.csv(paste0("OracleHoTMLE", n, ".csv"))[[2]]
tilde<-read.csv( paste0("oracleEICtilde", n, ".csv"))[[2]]
pn<-read.csv( paste0("oracleEIC", n, ".csv"))[[2]]
est_old <- read.csv( paste0("oracleOldTMLE", n, ".csv"))[[2]]

res1 <- c(sqrt(n) * mean(est - truth), n * var(est - truth))
res2 <- c(sqrt(n) * mean(est_old - truth), n * var(est_old - truth))
res1 <- round(c(res1, sqrt(sum(res1^2))),4)
res2 <- round(c(res2, sqrt(sum(res2^2))),4)
result <- cbind(data.frame(rbind(res1 , res2)), rep(NA,2), rep(NA,2))
colnames(result) <- c("bias", "variance", "SE", "abs_PntildeD2", "abs_PnD1")
rownames(result) <- c("HigherOrder", "FirstTMLE")
result[1,4] <- sqrt(n) * mean(abs(tilde))
result[1,5] <- sqrt(n) * mean(abs(pn))

kable(result)

truth <-0.7245819
n = 1000
print(n)
est <- read.csv(paste0("OracleHoTMLE", n, ".csv"))[[2]]
tilde<-read.csv( paste0("oracleEICtilde", n, ".csv"))[[2]]
pn<-read.csv( paste0("oracleEIC", n, ".csv"))[[2]]
est_old <- read.csv( paste0("oracleOldTMLE", n, ".csv"))[[2]]

res1 <- c(sqrt(n) * mean(est - truth), n * var(est - truth))
res2 <- c(sqrt(n) * mean(est_old - truth), n * var(est_old - truth))
res1 <- round(c(res1, sqrt(sum(res1^2))),4)
res2 <- round(c(res2, sqrt(sum(res2^2))),4)
result <- cbind(data.frame(rbind(res1 , res2)), rep(NA,2), rep(NA,2))
colnames(result) <- c("bias", "variance", "SE", "abs_PntildeD2", "abs_PnD1")
rownames(result) <- c("HigherOrder", "FirstTMLE")
result[1,4] <- sqrt(n) * mean(abs(tilde))
result[1,5] <- sqrt(n) * mean(abs(pn))

kable(result)

truth <-0.7245819
n = 1500
print(n)
est <- read.csv(paste0("OracleHoTMLE", n, ".csv"))[[2]]
tilde<-read.csv( paste0("oracleEICtilde", n, ".csv"))[[2]]
pn<-read.csv( paste0("oracleEIC", n, ".csv"))[[2]]
est_old <- read.csv( paste0("oracleOldTMLE", n, ".csv"))[[2]]

res1 <- c(sqrt(n) * mean(est - truth), n * var(est - truth))
res2 <- c(sqrt(n) * mean(est_old - truth), n * var(est_old - truth))
res1 <- round(c(res1, sqrt(sum(res1^2))),4)
res2 <- round(c(res2, sqrt(sum(res2^2))),4)
result <- cbind(data.frame(rbind(res1 , res2)), rep(NA,2), rep(NA,2))
colnames(result) <- c("bias", "variance", "SE", "abs_PntildeD2", "abs_PnD1")
rownames(result) <- c("HigherOrder", "FirstTMLE")
result[1,4] <- sqrt(n) * mean(abs(tilde))
result[1,5] <- sqrt(n) * mean(abs(pn))

kable(result)
```


```{r}

remotes::install_github("Larsvanderlaan/tmle3", ref = "updating_updater")

```



```{r}
sim_data <- function(n, bias = F) {
bound <- Vectorize(tmle3::bound)
D <- DAG.empty()
D <- D +
  node("Wcont", distr = "runif", min = -0.8 , max = 0.8) +
   node("W", distr = "rconst", const = round(Wcont, 1)) +
  node("W1cont", distr = "runif", min = -1, max = 1) +
   node("W1", distr = "rconst", const = round(W1cont, 1)) +
  node("g1", distr = "rconst", const =   bound(plogis( W1^2 - W1/2 + W^2 - 0.5*0.5 + 0.5*W - W*W1), 0.25)) +
  node("A", distr = "rbinom", size = 1,  prob = g1) +
    node("EY", distr = "rconst", const = plogis((A + W - A*W1/2 + W1*W - W^2 ))) +
  node("Y", distr = "rbinom", size =1 , prob = EY) +

  node ("EY1", distr = "rconst",  const = plogis((1 + W - 1*W1/2 + W1*W - W^2 )))
setD <- set.DAG(D, vecfun = c("bound"))
data <- sim(setD, n = n)
data <- as.data.table(data)
data
}
data_bias <- sim_data(50000 , F)
mean(data_bias$EY1)
data_bias

```



```{r}
truth <-0.7245553
n =750
tilde_true <- read.csv(paste0("simSearch/all_lambda_tilde_truth", n, ".csv"))[,-1]
pn_true <- read.csv( paste0("simSearch/all_lambda_Pn_truth", n, ".csv"))[,-1]
tilde <- read.csv(paste0("simSearch/all_lambda_tilde", n, ".csv"))[,-1]
pn <- read.csv(paste0("simSearch/all_lambda_Pn", n, ".csv"))[,-1]
est_old <- read.csv( paste0("simSearch/tmle_est", n, ".csv"))[,-1]
est_ho <- read.csv(paste0("simSearch/all_lambda_ho_tmle_est", n, ".csv"))[,-1]
est_first <- read.csv( paste0("simSearch/all_lambda_second_order_tmle", n, ".csv"))[,-1]
keep <- which(apply(est_ho, 2, function(v){sum(!is.na(v))}) > 50)

```


```{r}
sqrt((as.vector(apply((est_ho - truth)^2, 2, mean, na.rm = T))))
apply(abs(as.matrix(pn_true)) ,2 , mean, na.rm = T)

```
```{r}
sqrt(n) *as.vector(apply(tilde_true, 2, function(v){mean(abs(v), na.rm = T)}))
sqrt(n) *as.vector(apply(pn_true, 2, function(v){mean(abs(v), na.rm = T)}))[best[1:15]]
sqrt(n) *as.vector(apply(tilde, 2, function(v){mean(abs(v), na.rm = T)}))[best[1:15]]
sqrt(n) *as.vector(apply(pn, 2, function(v){mean(abs(v), na.rm = T)}))[best[1:15]]
```

```{r}
sqrt(n) * (as.vector(apply(as.matrix(est_old - truth), 2, mean, na.rm = T)))

sqrt(n) * sqrt(as.vector(apply(as.matrix(est_old - truth)^2, 2, mean, na.rm = T)))



se <- sqrt((as.vector(apply((est_ho - truth)^2, 2, mean, na.rm = T))))
best <- intersect(order(se), keep)
best[1:15]
sqrt(n) * se[best][1:15]
sqrt(n) * as.vector(apply(est_ho - truth, 2, mean, na.rm = T))[best][1:15]
```

```{r}
apply(est_ho, 2, function(v) {sum(!is.na(v))})

```

```{r}

as.vector(apply(as.matrix(est_old - truth), 2, mean, na.rm = T))
as.vector(apply(est_ho - truth, 2, mean, na.rm = T))
as.vector(apply(est_first - truth, 2,  mean, na.rm = T))


as.vector(apply(as.matrix(est_old - truth), 2, var, na.rm = T))
as.vector(apply(est_ho - truth, 2, var, na.rm = T))
as.vector(apply(est_first - truth, 2,  var, na.rm = T))

```
