# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

eval_basis <- function(x, basis) {
    .Call('_LTMLE_eval_basis', PACKAGE = 'LTMLE', x, basis)
}

integrate <- function(val, basis, lower, upper) {
    .Call('_LTMLE_integrate', PACKAGE = 'LTMLE', val, basis, lower, upper)
}

