branches:
  only:
    - master
    - devel

env:
  global:
    - RGL_USE_NULL=TRUE

language: r
sudo: false
cache: packages
cran: https://cran.rstudio.com

warnings_are_errors: true
r_build_args: '--no-manual'
r_check_args: '--no-build-vignettes --no-manual'

r:
  - release
  - devel

before_install:
  Rscript -e 'update.packages(ask = FALSE)'

r_packages:
  - devtools
  - covr

r_github_packages:
  - r-lib/covr
  - r-lib/sessioninfo

# coverage
after_success:
  - travis_wait 60 Rscript -e 'covr::codecov()'

notifications:
  email:
    on_success: change
    on_failure: change
